#!/usr/bin/env bash

add="rewrite ^/redirect(.*) https://www.google.com permanent;"
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed "/location \/ {/a $add" /etc/nginx/sites-available/default
sudo service nginx restart
