#!/usr/bin/env bash
# install and configure haproxy
apt update
apt install -y haproxy
service haproxy start
echo "
frontend web-balancer
        bind *:80
        stats uri /stats
        default_backend web-servers

backend web-servers
        balance roundrobin
        server 416693-web-01 100.25.181.103:80 check
        server 416693-web-02 54.160.70.20:80 check
" >>  /etc/haproxy/haproxy.cfg

service haproxy restart
