#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument
host=$1

if [ -z "$host" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$host"
fi
