#!/usr/bin/env bash
# kills the infinity and beyond  program using sigkill signal

# Get the pid of the program
id=$(pgrep "bash ./7-highlander" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
  kill -9 "$id"
fi
