#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i="1"
while [ $i -lt 21 ]
do
	echo $i
	if ((i == 4)); then
		echo "bad luck from China"
	elif ((i == 8)); then
		echo "bad luck from Japan"
	elif ((i == 17)); then
		echo "bad luck from Italy"
	fi
	i=$(( i + 1 ))
done