#!/usr/bin/env bash
# nginx must be listening on all active IPs on port 8080 with nginx as user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
nginx -t
nginx -s reload

